name: Update gist with WakaTime stats

on:
  schedule:
    - cron: "30 18 * * *"  # Runs every day at 12:00 AM IST (6:30 PM UTC)
  workflow_dispatch:       # Allows manual run from GitHub UI

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        run: node ./dist/index.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
